### PR TITLE
Theme experiment DO NOT merge

### PR DESCRIPTION
**Pull request by lbliii**
you didn't ask for this but i was in a creative mood and wanted to show you what an updated hugo docs site can look like for anyone curious! to preview, use a hugo version like 0.76.0.

### CODE REVIEW

**Comment by CryptoPishka** [comment]
@lbliii ohh that's very nice of you, thank you! how can I preview it (deploy preview failed). can't wait to see it!

**Comment by lbliii** [comment]
@CryptoPishka, It's previewable now. this is a very different theme/style based on tiles, but just to show that it can be molded into whatever you'd like. you can ingest feedback forms through slack if you upgrade netlify for form submissions and also override the default search for something more snazzy like algolia

**Comment by CryptoPishka** [comment]
oh wow, this is so cool! I like the Changelog, 'Contact' button, also the idea with 'cards' on the main page. That's awesome and I'm wondering what @rclagett thinks about it

**Comment by rclagett** [comment]
Wow @lbliii this is slick thanks!

Just a heads up, we are transitioning docs to another platform soon, within the next month or two I believe.

**Comment by lbliii** [comment]
> Wow @lbliii this is slick thanks!
> 
> Just a heads up, we are transitioning docs to another platform soon, within the next month or two I believe.

I know, no worries! It was more of me wanting to show you guys the versatility of it for any of your future / personal projs. ( i'm slightly obsessed with it and it's driven me to learn a bit more about front-end design haha.)

**Pull request closed without merging**
