### PR TITLE
AWS Cost Report

### PR DESCRIPTION
**Pull request by lbliii**
I wasn't able to find an example of some of the utilization metrics that I saw in the old do (Network, memory utilization, get/put requests). Are they still available as util metrics or does it depend on config?

Also, is the context of the aggregation table limited to EC2 or is it global for all three?

### CODE REVIEW

**Review by CryptoPishka — COMMENTED** [review]
"The AWS Cost report is generated once per week and may take up to 7 days after setup to display your first analysis." - with the new pipeline, it runs daily now. @TheConnMan will be able to confirm but this is what I see in the logs

**Comment by CryptoPishka** [comment]
> 
>     EC2 elements without a Agent / Windows agent display only two utilization measures: Active Hours and CPU Utilization %.
>     EC2 elements with a Agent installed have the following additional utilization metrics available: Memory Utilization %, Disk I/O %, and Disk Space Used %.
>     EC2 elements with a Windows agent installed have the Network I/O % metric available.
> 
> If you have a mix of elements with and without a Agent, you will see gaps in the utilization figures where values are not available.

Here, we need to replace Agent/Windows agent with 'CloudWatch Agent'. We rely solely on CloudWatch Agent memory metric in the new reports.

**Comment by TheConnMan** [comment]
> "The AWS Cost report is generated once per week and may take up to 7 days after setup to display your first analysis." - with the new pipeline, it runs daily now. @TheConnMan will be able to confirm but this is what I see in the logs

Confirmed.

**Comment by rclagett** [comment]
> I wasn't able to find an example of some of the utilization metrics that I saw in the old do (Network, memory utilization, get/put requests). Are they still available as util metrics or does it depend on config?
> 
> Also, is the context of the aggregation table limited to EC2 or is it global for all three?

Hey @lbliii I'm going to follow up on this in #cw-team-content as I need some assistance from the rest of the team to confirm.

**Comment by rclagett** [comment]
> > I wasn't able to find an example of some of the utilization metrics that I saw in the old do (Network, memory utilization, get/put requests). Are they still available as util metrics or does it depend on config?
> > Also, is the context of the aggregation table limited to EC2 or is it global for all three?
> 
> Hey @lbliii I'm going to follow up on this in #cw-team-content as I need some assistance from the rest of the team to confirm.

Hey @lbliii so below is the exhaustive list of metrics for each type in these new reports:

EC2
-CPU Utilization %
-Memory Utilization %
RDS
-CPU Utilization %
-Disk Space Used %
-Disk I/O %
S3
-Bucket Size (bytes)
-Number of Objects
-Put Requests
-Get Requests

All others that existed in the old reports can be omitted. Note that IOPS Utilization % went away for RDS but Disk I/O % was added.

**Review by rclagett — CHANGES_REQUESTED** [review]
Other than the updates previously mentioned (CloudWatch agent instead of Linux and Windows agents & Removing old metrics that no longer exist) this is good to go!

Re-request my review when another draft is ready thanks!

**Review by rclagett — APPROVED** [review]
Thank you @lbliii !!!

**Pull request merged**
