### PR TITLE
Remove all references to Events

### PR DESCRIPTION
**Pull request by rclagett**

### CODE REVIEW

**Review by CryptoPishka — APPROVED** [review]
LGTM, thanks Ryan!

**Comment by rclagett** [comment]
Thanks for the first pass review @CryptoPishka! Could you please look at my second commit and provide a new review?

**Review by jags2480 — APPROVED** [review]
Looks good to me too Ryan.

**Comment by CryptoPishka** [comment]
> Thanks for the first pass review @CryptoPishka! Could you please look at my second commit and provide a new review?

looking at the second commit

**Review by CryptoPishka — APPROVED** [review]

**Pull request merged**
