### PR TITLE
Cost reports

### PR DESCRIPTION
**Pull request by lbliii**
I added a part three to the CUR page for linking accounts and tried to provide more context similar to the tooltip on the BETA tab. I also performed a find + replace for "master billing", as AWS has moved away from the term.  

I didn't add a full tabbed screenshot to avoid it going out of date but happy to add one anyway!

### CODE REVIEW

**Review by CryptoPishka — CHANGES_REQUESTED** [review]
> its associated member accounts. member accounts

Member has to start with capital M

**Review by rclagett — APPROVED** [review]

**Comment by rclagett** [comment]
Thank you @lbliii these are wonderful! I also love the tab name "Linked Accounts". I'm going to _highly_ recommend we go with this text in the UI.

**Comment by rclagett** [comment]
> > its associated member accounts. member accounts
> 
> Member has to start with capital M

@CryptoPishka I think it's okay to leave the "m" in member and management accounts as lower case as AWS does the same: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html

If you agree, could you change your review to approved?

**Review by CryptoPishka — APPROVED** [review]
approving this PR. great job Lawrence, ty!

**Comment by rclagett** [comment]
Waiting to merge this until the UI changes go out.

**Pull request merged**
