### PR TITLE
Cw agent

### PR DESCRIPTION
**Pull request by lbliii**
This is a first pass at a CW agent page with minimal reproduction of installation steps. It points out install options and highlights the main difference being that they must use the provided json for their conf file. 

- i have a placeholder for what is considered a large > # client/environment. something like this is probably helpful when people are trying to decide how important this agent is to install for faster reports.

- the tip at the very end is something I read in the AWS documentation. Does it apply here? or should i swap that IAM role with the ones we have them install and link to that documentation? 

- do you prefer this brief version or would you like it to reproduce a certain version of the steps like CLI?

### CODE REVIEW

**Comment by CryptoPishka** [comment]
while we are working on your Slack access, here are my comments (posted in Slack thread that you'll be able to see soon):

**Comment by lbliii** [comment]
Updated! Since we simplified it by removing the 1-3 step structure, i felt like the end content was less relevant and removed it. happy to add it back if you prefer.

**Comment by CryptoPishka** [comment]
@lbliii renaming back to CW Agent (removing Linux). I think we'll add Windows section on the same page.

Need your help with formatting Tips section:

- steps 2, 8 and 9:  command line is too long. Possible to split into 2 lines?
- step 7: [following][2] should redirect to the Linux Agent Config File . Hyperlink doesn't work;
- step 9: workaround steps should be as a list with three commands being copied to clipboard separately.

Everything else looks good, thank you!

**Comment by lbliii** [comment]
the links seem to break if wrapped in the notice shortcode so i've removed that. I'm unsure why the notice shortcodes are breaking right now, it doesnt seem like we've changed anything related

**Pull request merged**
