### PR TITLE
Azure int update

### PR DESCRIPTION
**Pull request by lbliii**
Hey Andrew, I actually drafted a new version for this a few weeks ago before the rebranding but forgot to update and follow up with a PR.  I apologize!

### CODE REVIEW

**Comment by TheConnMan** [comment]
@andrewpaine if you're good with this can you approve? You are closer to this than @rclagett and me. Thanks.

**Comment by andrewpaine** [comment]
@TheConnMan I added quite a few comments yesterday but didn't submit the review 🤦‍♂

**Comment by lbliii** [comment]
@rclagett , I've made the changes andrew suggested -- this should be ready now.

**Comment by rclagett** [comment]
LGTM thanks!

**Comment by rclagett** [comment]
Looks like there are some conflicts you'll have to resolve before merging.

**Pull request merged**
